---
startDelaySeconds: 0
# hostPort: 8081
username: 
password: 
jmxUrl: service:jmx:rmi:///jndi/rmi://127.0.0.1:1234/jmxrmi
ssl: false
# lowercaseOutputName: false
# lowercaseOutputLabelNames: false
# whitelistObjectNames: ["org.apache.cassandra.metrics:*"]
# blacklistObjectNames: ["org.apache.cassandra.metrics:type=ColumnFamily,*"]
lowercaseOutputLabelNames: true
lowercaseOutputName: true
whitelistObjectNames: ["java.lang:type=OperatingSystem"]
blacklistObjectNames: []
rules:
  # - pattern: 'org.apache.cassandra.metrics<type=(\w+), name=(\w+)><>Value: (\d+)'
  #   name: cassandra_$1_$2
  #   value: $3
  #   valueFactor: 0.001
  #   labels: {}
  #   help: "Cassandra metric $1 $2"
  #   cache: false
  #   type: GAUGE
  #   attrNameSnakeCase: false
  - pattern: 'java.lang<type=OperatingSystem><>(committed_virtual_memory|free_physical_memory|free_swap_space|total_physical_memory|total_swap_space)_size:'
    name: os_$1_bytes
    type: GAUGE
    attrNameSnakeCase: true
  - pattern: 'java.lang<type=OperatingSystem><>((?!process_cpu_time)\w+):'
    name: os_$1
    type: GAUGE
    attrNameSnakeCase: true